### ISSUE TITLE
vxwoks kernal replacement

### ISSUE THREAD

**Issue by moizzzz** [forth32/balong-fbtools#2]
some providers just lock in vxworks some lock in vxworks+nvram 
if the lock in nvram i can unlock through oem coad.
how to replace vxworks kernel for remove lock permanently?

**Comment by forth32** [comment]
Simply reflash vxworks partition. You can get it from unbranded frimware with same version.
Flash it in fastboot mode (with fastboot flash), from command line inside modem (with busybox nandwrite), or you can totally reflash modem with unbranded firmware.

-- 
Alexander Stepanov

**Comment by moizzzz** [comment]
i read all of your post but u not add clearly how to enter device to fastboot mode in simpe way .you just creat shortcut script for fastboot mode.you just type step by step and all of this function.

**Comment by moizzzz** [comment]
some provider lock  vxworks partition .u can not flash with .exe or .bin because modem has high security.i am finding method like boot pin. boot pin method is very best method but i want to unlock (vxworks replace) without open .firstly i unlock e8372h-153 through command line 1>at^sfm=1 2>at^godload 3>go_hdcl.exe and simple flash with flasher 2.0  but after fw update first command factry mode not working(at^sfm=1) kindly give me opnion how i can unlock without open
